/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Coordinator, CoordinatorInterface } from "../Coordinator";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IAccessControlApplication",
        name: "_stakes",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "_timeout",
        type: "uint32",
      },
      {
        internalType: "uint16",
        name: "_maxDkgSize",
        type: "uint16",
      },
      {
        internalType: "address",
        name: "_admin",
        type: "address",
      },
      {
        internalType: "contract IERC20",
        name: "_currency",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_feeRatePerSecond",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "node",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "aggregatedTranscriptDigest",
        type: "bytes32",
      },
    ],
    name: "AggregationPosted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "DefaultAdminDelayChangeCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint48",
        name: "newDelay",
        type: "uint48",
      },
      {
        indexed: false,
        internalType: "uint48",
        name: "effectSchedule",
        type: "uint48",
      },
    ],
    name: "DefaultAdminDelayChangeScheduled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "DefaultAdminTransferCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint48",
        name: "acceptSchedule",
        type: "uint48",
      },
    ],
    name: "DefaultAdminTransferScheduled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "successful",
        type: "bool",
      },
    ],
    name: "EndRitual",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint16",
        name: "oldSize",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "newSize",
        type: "uint16",
      },
    ],
    name: "MaxDkgSizeChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "participant",
        type: "address",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "word0",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "word1",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "word2",
            type: "bytes32",
          },
        ],
        indexed: false,
        internalType: "struct BLS12381.G2Point",
        name: "publicKey",
        type: "tuple",
      },
    ],
    name: "ParticipantPublicKeySet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
    ],
    name: "StartAggregationRound",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "authority",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "participants",
        type: "address[]",
      },
    ],
    name: "StartRitual",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "oldTimeout",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "newTimeout",
        type: "uint32",
      },
    ],
    name: "TimeoutChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "node",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "transcriptDigest",
        type: "bytes32",
      },
    ],
    name: "TranscriptPosted",
    type: "event",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "INITIATOR_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TREASURY_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "acceptDefaultAdminTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "application",
    outputs: [
      {
        internalType: "contract IAccessControlApplication",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
    ],
    name: "beginDefaultAdminTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelDefaultAdminTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint48",
        name: "newDelay",
        type: "uint48",
      },
    ],
    name: "changeDefaultAdminDelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "nodes",
        type: "address[]",
      },
    ],
    name: "cohortFingerprint",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "currency",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultAdminDelay",
    outputs: [
      {
        internalType: "uint48",
        name: "",
        type: "uint48",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultAdminDelayIncreaseWait",
    outputs: [
      {
        internalType: "uint48",
        name: "",
        type: "uint48",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeRatePerSecond",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
    ],
    name: "getAuthority",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
    ],
    name: "getParticipantFromProvider",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "provider",
            type: "address",
          },
          {
            internalType: "bool",
            name: "aggregated",
            type: "bool",
          },
          {
            internalType: "bytes",
            name: "transcript",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "decryptionRequestStaticKey",
            type: "bytes",
          },
        ],
        internalType: "struct Coordinator.Participant",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
    ],
    name: "getParticipants",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "provider",
            type: "address",
          },
          {
            internalType: "bool",
            name: "aggregated",
            type: "bool",
          },
          {
            internalType: "bytes",
            name: "transcript",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "decryptionRequestStaticKey",
            type: "bytes",
          },
        ],
        internalType: "struct Coordinator.Participant[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_provider",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_ritualId",
        type: "uint256",
      },
    ],
    name: "getProviderPublicKey",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "word0",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "word1",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "word2",
            type: "bytes32",
          },
        ],
        internalType: "struct BLS12381.G2Point",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
    ],
    name: "getPublicKeyFromRitualId",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "word0",
            type: "bytes32",
          },
          {
            internalType: "bytes16",
            name: "word1",
            type: "bytes16",
          },
        ],
        internalType: "struct BLS12381.G1Point",
        name: "dkgPublicKey",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "word0",
            type: "bytes32",
          },
          {
            internalType: "bytes16",
            name: "word1",
            type: "bytes16",
          },
        ],
        internalType: "struct BLS12381.G1Point",
        name: "dkgPublicKey",
        type: "tuple",
      },
    ],
    name: "getRitualIdFromPublicKey",
    outputs: [
      {
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "providers",
        type: "address[]",
      },
      {
        internalType: "uint32",
        name: "duration",
        type: "uint32",
      },
    ],
    name: "getRitualInitiationCost",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
    ],
    name: "getRitualState",
    outputs: [
      {
        internalType: "enum Coordinator.RitualState",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
    ],
    name: "getRoleAdmin",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "size",
        type: "uint16",
      },
    ],
    name: "getThresholdForRitualSize",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "hasRole",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "providers",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "authority",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "duration",
        type: "uint32",
      },
      {
        internalType: "contract IEncryptionAuthorizer",
        name: "accessController",
        type: "address",
      },
    ],
    name: "initiateRitual",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "isInitiationPublic",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
    ],
    name: "isRitualFinalized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "makeInitiationPublic",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "maxDkgSize",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "numberOfRituals",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingDefaultAdmin",
    outputs: [
      {
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
      {
        internalType: "uint48",
        name: "schedule",
        type: "uint48",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingDefaultAdminDelay",
    outputs: [
      {
        internalType: "uint48",
        name: "newDelay",
        type: "uint48",
      },
      {
        internalType: "uint48",
        name: "schedule",
        type: "uint48",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "pendingFees",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
      {
        internalType: "bytes",
        name: "aggregatedTranscript",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "word0",
            type: "bytes32",
          },
          {
            internalType: "bytes16",
            name: "word1",
            type: "bytes16",
          },
        ],
        internalType: "struct BLS12381.G1Point",
        name: "dkgPublicKey",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "decryptionRequestStaticKey",
        type: "bytes",
      },
    ],
    name: "postAggregation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
      {
        internalType: "bytes",
        name: "transcript",
        type: "bytes",
      },
    ],
    name: "postTranscript",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
    ],
    name: "processPendingFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "role",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "rituals",
    outputs: [
      {
        internalType: "address",
        name: "initiator",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "initTimestamp",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "endTimestamp",
        type: "uint32",
      },
      {
        internalType: "uint16",
        name: "totalTranscripts",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "totalAggregations",
        type: "uint16",
      },
      {
        internalType: "address",
        name: "authority",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "dkgSize",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "threshold",
        type: "uint16",
      },
      {
        internalType: "bool",
        name: "aggregationMismatch",
        type: "bool",
      },
      {
        internalType: "contract IEncryptionAuthorizer",
        name: "accessController",
        type: "address",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "word0",
            type: "bytes32",
          },
          {
            internalType: "bytes16",
            name: "word1",
            type: "bytes16",
          },
        ],
        internalType: "struct BLS12381.G1Point",
        name: "publicKey",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "aggregatedTranscript",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rollbackDefaultAdminDelay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "newSize",
        type: "uint16",
      },
    ],
    name: "setMaxDkgSize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "word0",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "word1",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "word2",
            type: "bytes32",
          },
        ],
        internalType: "struct BLS12381.G2Point",
        name: "_publicKey",
        type: "tuple",
      },
    ],
    name: "setProviderPublicKey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IReimbursementPool",
        name: "pool",
        type: "address",
      },
    ],
    name: "setReimbursementPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "ritualId",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "authority",
        type: "address",
      },
    ],
    name: "setRitualAuthority",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "newTimeout",
        type: "uint32",
      },
    ],
    name: "setTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "timeout",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalPendingFees",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdrawTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Coordinator__factory {
  static readonly abi = _abi;
  static createInterface(): CoordinatorInterface {
    return new utils.Interface(_abi) as CoordinatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Coordinator {
    return new Contract(address, _abi, signerOrProvider) as Coordinator;
  }
}
